INSTALL.md, README.md
Fixes https://github.com/knadh/listmonk/issues/10
=> fix: docker-compose command

README.md, frontend/src/Campaign.js, frontend/src/Campaigns.js, frontend/src/Dashboard.js, frontend/src/Import.js, frontend/src/Layout.js, frontend/src/Lists.js, frontend/src/Subscriber.js, frontend/src/Subscribers.js, frontend/src/Templates.js, frontend/src/index.css
=> Responsive design

main.go
Adds support to read config variables from env.
=> feat: read config from env

public.go
I get an internal server error, when I want to use the subscribe endpoint in a custom angular form.
=> fix: status code on success

frontend/src/views/Subscribers.vue
Fixes a bug left out by the recent refactor
Same as the second commit in #151, just updated to match your recent refactor
=> frontend: pass query when changing lists for subscribers

Dockerfile
Including an EXPOSE instruction in the Dockerfile (#275)
=> Including an EXPOSE instruction in the Dockerfile

.github/workflows/release.yml, .goreleaser.yml
This PR automates the (current) manual build process via Github Actions. In order for this to work, please add the following Secrets to the Repo here: https://github.com/knadh/listmonk/settings/secrets/actions
- `DOCKERHUB_TOKEN`: Generate a new Token from Dockerhub (https://hub.docker.com/settings/security)
- `DOCKERHUB_USERNAME`: `listmonk` (I think)
- `GORELEASER_TOKEN`: Generate a new Token from Github (https://github.com/settings/tokens)
**Note**: Configured the pipeline to only trigger when you push a new tag of the format `v*` (for eg `v0.1.0).
=> Add GitHub Actions

Makefile
Signed-off-by: Tamal Saha <tamal@appscode.com>
=> Build static Go binary

docker-compose.yml
Signed-off-by: Tamal Saha <tamal@appscode.com>
=> Fix indentation of docker-compose file

Dockerfile
=> chore(dockerfile): not are using multi-stage build

i18n/ru.json
=> Typo in ru.json

install-prod.sh
Closes https://github.com/knadh/listmonk/issues/422
=> fix colorized output in terminal

README.md
Change directory to newly created before running install script
=> CD to directory before install script

go.mod, go.sum, internal/media/providers/s3/s3.go
This commit switches simples3 from issuing a POST to a PUT call for file uploads.
Ref #617
=> feat: switch from s3 POST to s3 put

schema.sql
=> Use empty logo_url as default

go.mod, go.sum
=> feat: bump simples3 for digitalocean support

frontend/src/components/Editor.vue
This adds the `anchor` plugin to TinyMCE. This is especially helpful for table of contents within newsletters.
[Anchor plugin docs](https://www.tiny.cloud/docs/plugins/opensource/anchor/)
=> Activate anchor plugin (TinyMCE)

i18n/pt-BR.json
=> Fix pt-BR subscription form header

go.mod, go.sum, internal/messenger/postback/postback.go, internal/messenger/postback/postback_easyjson.go
This commit allows postback messengers to access attachment, from email (campaign level).
ref: https://github.com/joeirimpan/listmonk-messenger/blob/master/messenger/ses.go
=> feat(postback): Add attachment, from email to postback body

internal/bounce/webhooks/ses.go
Issue: https://github.com/knadh/listmonk/issues/1122
=> Ses bounce notif type

docs/swagger/collections.yaml
Related to [Issue 764](https://github.com/knadh/listmonk/issues/764)
Created a swagger collection for Listmonk APIs. Mostly relied on Listmonk docs and handlers.go
There are a few endpoints missing in the collection, will update it in future PRs.
=> added swagger collection for APIs

docs/docs/content/apis/subscribers.md
I've expanded the docs a bit, related to #995
=> Expanded docs about PUT /api/subscribers/:id

frontend/src/views/Maintenance.vue, i18n/ca.json, i18n/cs-cz.json, i18n/cy.json, i18n/de.json, i18n/en.json, i18n/es.json, i18n/fi.json, i18n/fr.json, i18n/hu.json, i18n/it.json, i18n/jp.json, i18n/ml.json, i18n/nl.json, i18n/pl.json, i18n/pt-BR.json, i18n/pt.json, i18n/ro.json, i18n/ru.json, i18n/se.json, i18n/sk.json, i18n/tr.json, i18n/vi.json, i18n/zh-CN.json, i18n/zh-TW.json
I added the translation for all languages.
=> Add missing translation message in maintenance page

docs/docs/content/apis/campaigns.md, docs/docs/content/apis/import.md, docs/docs/content/apis/media.md, docs/docs/content/apis/subscribers.md, docs/docs/content/apis/templates.md, internal/captcha/captcha.go, internal/core/campaigns.go, internal/core/subscribers.go, internal/core/subscriptions.go, internal/subimporter/importer.go
- Fixed typos in comments and error messages
- Fixed indentation for markdown tables in markdown files
=> Fix typos in comments

queries.sql
=> Fix typo in queries.sql

docs/docs/content/configuration.md
=> Update configuration.md - media uploads

docs/docs/content/installation.md
added "tutorials" section and other minor edits
=> added "tutorials" section and other minor edits

Makefile, docs/docs/content/configuration.md, docs/docs/content/developer-setup.md, docs/docs/content/installation.md, docs/docs/content/upgrade.md, install-demo.sh, install-prod.sh
Fixes https://github.com/knadh/listmonk/issues/1431
=> fix: replace docker-compose with docker compose

docs/docs/content/installation.md
=> Update installation.md - Add note about docker version

internal/messenger/postback/postback.go
=> Fix attachments being omitted from postback

docs/docs/content/upgrade.md
https://github.com/knadh/listmonk/issues/1113#issuecomment-1359108192
=> Update upgrade.md +binary info

internal/messenger/postback/postback.go, internal/messenger/postback/postback_easyjson.go
fixes https://github.com/knadh/listmonk/issues/1621
=> feat: Add `from_email` to postback struct for sending tx postbacks

docs/docs/content/configuration.md
* https://github.com/knadh/listmonk/issues/1462
* https://github.com/knadh/listmonk/issues/13#issuecomment-516259910
=> Update configuration.md +logs section

docs/docs/content/installation.md
=> Update installation.md +tut & minor changes

docs/docs/content/bounces.md
This update includes complete instructions for configuring Amazon Simple Email Service with listmonk's bounce processing. It also adds instructions for exporting bounces from issue #863.
=> Improve SES bounce processing docs

schema.sql
https://github.com/knadh/listmonk/issues/1668#issuecomment-1890768681
=> Update schema.sql - change default bounce settings

docs/site/layouts/index.html
The Railway icon has been fixed and the alt description has also been corrected.
fixes #1695
=> fixed railway icon and spelling bug (#1695)

docs/docs/content/installation.md
This is what I meant. I'm not 100% sure this is correct or the best way to word it.
=> Update installation.md - choosing a binary, amd64 info

frontend/src/components/ListSelector.vue
Fixes https://github.com/knadh/listmonk/issues/1748
=> fix: usage of translated string in subscriber form

frontend/src/views/Subscribers.vue
Fixes https://github.com/knadh/listmonk/issues/1736
=> fix: empty list breaks subscriber page

docs/docs/content/installation.md
As @knadh suggested (on https://github.com/knadh/listmonk/issues/1844), I added the kubernetes helm installation instructions to docs 💐
=> Add kubernetes helm installation instructions to docs

queries.sql
On update sql statements need delete only defined ids not all rows in the table.
solve: https://github.com/knadh/listmonk/issues/1770
=> fix vanishing attachments in campaign in more the one campaigns setup

cmd/subscribers.go, frontend/src/views/Subscribers.vue, internal/core/subscribers.go, queries.sql
=> fix #1950:Export of unsubscribed users exports all users

docs/docs/content/apis/bounces.md
=> adding docs for bounces api

docs/docs/content/apis/lists.md
Added missed-out documentation at lists.md for public lists api.
=> adding lists docs for public lists api

docs/docs/content/installation.md
Hey there, we recently revamped our one-click "Deploy to Elestio" button, this pull request is regarding updating it in the Readme file.
- Fixes #2004
=> chore: Deploy to Elestio button updated

docs/docs/content/installation.md, docs/site/layouts/index.html
This PR adds Zeabur as the hosting provider: https://zeabur.com/templates/5EDMN6
**Site**
**Content**
=> docs: Add Zeabur one-click button

docs/docs/content/apis/subscribers.md
updating the api docs of subscribers with missing API.
=> update subscribers api docs

docs/docs/content/apis/campaigns.md
updating the api docs of campaigns with missing API.
=> updating campaigns api doc

cmd/init.go
Removed Validations as it is handled in the manager.New() method.
=> <master> [abhinandkakkadi] Removed redundant init validations (minor)

i18n/en.json
"User(s) couldn't updated" -> "User(s) couldn't be updated"
=> [i18n] Fix typo

i18n/de.json
DE: "Du hast dich für folgende**n** Listen angemeldet:" -> "Du hast dich für folgende Listen angemeldet:"
=> Fixed Typo

docs/docs/content/installation.md, docs/site/layouts/index.html
=> elest.io image fixed docs

static/public/templates/index.html
There is no matching anchor tag to the closing anchor inside the if condition.
=> fix(static): no matching closing anchor tag

docs/docs/content/apis/subscribers.md
=> Fix typos in subscribers.md

docs/site/layouts/index.html
This adds Nodion as a deployment option to the static website. Thanks :)
=> Add Nodion Deployment Option

docs/docs/content/apis/sdks.md
=> Add link for n8n node

cmd/auth.go, cmd/init.go, internal/manager/manager.go
Improved security measures
1. 65eeaca3127c665b4292d2ffca93141ce50fb40c - removed `getHostByName` sprig function, which allows [DNS queries](https://masterminds.github.io/sprig/network.html) 
2. 836a017f9dd2ba970d6fd53ee95ee0591f026f9c - improved constant time comparison protection mechanism, which was previously being skipped due to a logical error.
=> Security enhancements
