knadh/listmonk

- README.md
- Add suggestion to place the listmonk binary and config file in a separate folder instead of cluttering the default downloads folder
> update instructions for local installation

- admin.go
- campaigns.go
- handlers.go
- install.go
- lists.go
- main.go
- manager/manager.go
- media.go
- messenger/emailer.go
- messenger/messenger.go
- public.go
- subimporter/importer.go
- subscribers.go
- templates.go
- utils.go
- unchecked returns fixed (most)
- remove unused constants
- remove unsed structs
- function parameters unused or incorrectly used
- removed if else chains for error checks
- use regex MustCompile instead of compile
- spell checks
- preallocate slice cap when size known
- scope issues inside range
> chore: minor refactors based on static checks

- README.md
The Heroku deploy button provides automated one-click deployments to Heroku.
I thinks this is especially helpful for users to quickly get started with listmonk. 
Note:
The deploy button is currently in test and I haven't used it in production, yet.
> Add note about Heroku deploy button

- frontend/src/Campaign.js
Removes appending root URI in `img src` from frontend which broke the rendering
of S3 URLs in campaign templates.
Closes https://github.com/knadh/listmonk/issues/101
> fix: Remove root URI on frontend

- frontend/vue.config.js
Currently, recompiling and serving the frontend breaks when listmonk is behind a caching proxy, like Cloudflare.
Vue supports cache busting, which adds a digest hash of the file to the name of all js, css, and other frontend assets. This allows the latest versions to be served easily when the listmonk binary is updated.
> frontend: Enable vue filenameHashing

- .gitignore
- .goreleaser.yml
- Dockerfile
- INSTALL.md
- README.md
- config-demo.toml
- docker-compose.yml
This PR makes the following changes:
- Add  `config-demo.toml` to `Dockerfile` which uses the db host
`demo-db`. This is more suited for demo setups. For normal docker installations
the db host is changed back to `db` which is a better sane default.
- Reworded `INSTALL.md` and `README.md` for more clarity on docker
installation and configuration.
> feat: Add separate config for demo setup, tweak docs

- frontend/src/App.vue
This PR has a fix for inconsistent active sidebar link on routing to links not in groups.
<details>
<summary>Previous Behaviour</summary>
</details>
<details>
<summary>After Fix</summary>
>
</details>
**This problem occurs when navigating from a group item to a non group item**. There are two problems to be solved here.
1. The group item is not collapsed.
1. The active state is not transferred.
We watch the route and change the `activeGroup` based on the current route. The `expanded` attribute of the `b-menu-item` component is overridden to toggle based on the value of the relevant key in the `activeGroup` object. 
https://github.com/knadh/listmonk/blob/0f055eacb87030b55970f4870ff3a0b22b0dcaef/frontend/src/App.vue#L135-L142
Here, on navigating to a non group item, the route `meta` does …
> fix: inconsistent active link on sidebar navigation

- frontend/src/App.vue
- frontend/vue.config.js
This PR has a fix for inconsistent sidebar toggle for group items.
<details>
<summary>Previous Behaviour</summary>
</details>
<details>
<summary>After Fix</summary>
</details>
Unlike the previous problem (fixed [here](https://github.com/knadh/listmonk/pull/181)), this problem occurs when navigating between group items. From the [buefy docs](https://buefy.org/documentation/menu/) the behaviour that is intended is for only one group to be expanded at a time. This is not happening properly.
There is a peculiar collapse behaviour as seen below. 
<details>
<summary>Another peculiar behaviour</summary>
</details>
The reason such a behaviour exists is that the state of the component is managed by our code using `activeGroup`. We watch the route and change the `activeGroup` based on the current …
> fix: inconsistent sidebar group toggle on navigation

- Makefile
Git tag version injected via Makefile is incorrect since `git describe` doesn't consider annotated tags but all the recent releases are lightweight tags. So instead use `git describe --tags` command which also considers recent lightweight tag.
Related  #197
> fix: incorrect git tag being injected as version

- frontend/src/views/Import.vue
The example given for CSV import on `Import.vue` is incorrect since field `attributes` value is not a valid JSON. The previous example copy-pasted was throwing following CSV parse error.
```
2020/10/03 17:59:38 processing 'email-sample.csv'
2020/10/03 17:59:38 error reading CSV 'parse error on line 2, column 28: bare " in non-quoted-field'
```
Previous incorrect example  
```
email,name,attributes
user1@mail.com,"User One",{'"{""age"": 42, ""planet"": ""Mars""}"'}
user2@mail.com,"User Two", {'"{""age"": 24, ""job"": ""Time Traveller""}"'}
```
Should ideally be something like below
```
email,name,attributes
user1@mail.com,"User One","{""age"": 42, ""planet"": ""Mars""}"
user2@mail.com,"User Two","{""age"": 24, ""job"": ""Time Traveller""}"
```
> fix: incorrect csv import example on frontend

- internal/subimporter/importer.go
According to [RFC6532](https://tools.ietf.org/html/rfc6532) unicode characters are supported in email address but the in-built custom regex was only validating ASCII characters.
> fix: use mail.ParseAddress to validate email instead of custom regex

- README.md
- install-demo.sh
Adds a simple `shell` script to setup a demo installation of `listmonk`.
> feat: Add shell script for demo setup

- .goreleaser.yml
Based on https://github.com/knadh/listmonk/commit/afef994e6d66b8e881924cb8cbe30f20e1507474
the binary variable `BIN` was changed. The same needs to be updated
in `.goreleaser.yml` config as well.
> chore: Pass the binary path correctly to `make`

- internal/manager/manager.go
Closes #270
According to https://stackoverflow.com/questions/34348072/go-html-comments-are-not-rendered
> Adding Safe templating function for keeping HTML comments

- frontend/src/views/Subscribers.vue
When showing the list of subscribers the links to the lists the subscriber is a member of wrongly use the subscribers ID instead of the list's ID.
> Fix wrong list links in subscribers overview

- .github/workflows/release.yml
Since `GITHUB_TOKEN` is automatically injected in build
pipelines, we don't need to generate and add our custom token here.
> fix: rename Github Token secret variable

- frontend/src/views/TemplateForm.vue
Issue:
1. Added : for placeholder property
2. Added `rawHTML` under `fields` namespace
https://github.com/knadh/listmonk/blob/6dbcfee0801148c23cbb0444d15c7dce28bd672d/frontend/src/views/TemplateForm.vue#L19
> Fix: campaign field names

- config-demo.toml
- config.toml.sample
See commit message comments for details. The TOML formatting wasn't invalid, it's just non-traditional and annoyed me a lot. The other two changes to sample configs are just sysadmin convenience and more safety out of the box.
> Cleanup sample config

- cmd/handlers.go
Fixes https://github.com/knadh/listmonk/issues/380
If basic auth is enabled, the endpoint will still respond with 200.
```sh
curl -i localhost:9000/api/health
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Date: Wed, 02 Jun 2021 14:38:47 GMT
Content-Length: 14
{"data":true}
```
> fix: expose healthcheck API as public endpoint

- README.md
- docker-compose.yml
- install-demo.sh
- install-prod.sh
- Add a shell script to orchestrate a production setup with
`docker-compose`. The script fetches config and `docker-compose.yml`
from the `master` branch, generates a secure password, performs DB
migrations and starts the container services.
- Add a health check for Postgres container service in `docker-compose.yml`.
- Add cusotm `container_name` for services inside `docker-compose`.
This is helpful to check the status of containers in the install shell script.
> feat: Add easy install script

- Makefile
Hi,
I’m glad I’ve found this "little" gem and I’ve been working on [a deb package](https://git.hack-hro.de/kmohrf/listmonk-deb) for the past three hours and have encountered a few bumps along the road. It comes down to these two issues:
* Debian installs yarn as `yarnpkg`. This first commit fixes this by simply allowing the caller to override the yarn binary name. This also make it easier to pass options (i.e. for npm caching servers).
* I’ve noticed that the `dist` make target will execute builds each time it’s called and is missing a dependency on the `deps` target. I’ve split up the latter into dedicated targets for `stuffbin` and `node_modules` so that each of them is only executed when necessary. I’ve also defined dependencies for the build targets so that rebuilds should only get …
> streamline make configuration

- listmonk@.service
As suggested in #409 and documented in #411 this PR adds a systemd service unit as a basis for package maintainers and should even be usable as a drop-in unit for linux distributions that use systemd as its init system as long as the listmonk binary resides in `/usr/bin/listmonk`.
Any comments or questions are appreciated :).
> add systemd service unit

- static/email-templates/campaign-status.html
The campaign status had a broken link:
```
<a href="http:///campaigns/14" target="_blank">Test Newsletter 4</a>
```
> Fix RootURL in campaign-status.html

- install-demo.sh
- install-prod.sh
There was a mix of tabs and spaces in the install shell scripts. This should migrate all of them to tabs.
> Fix whitespace inconsistency in install scripts

- cmd/install.go
Pressing enter without specifying a letter in the continue prompt cancells installation. So, the script should show as such.
> Clarify default option in prompt

- Makefile
non-GNU systems like FreeBSD and illumos do not understand the long
"--no-create" flag to touch. POSIX defines that conforming implementations
must understand "-c" for this, so use the flag that is widely understood
(including by GNU touch).
<https://pubs.opengroup.org/onlinepubs/9699919799/utilities/touch.html>
> Use POSIX standard -c flag for "touch"

- Makefile
When building on a system with enough cores, there is a race condition where
make runs pack-bin before build-frontend is complete.
Running: /usr/bin/gmake -j 60 dist
go install github.com/knadh/stuffbin/...
CGO_ENABLED=0 go build -o listmonk -ldflags="-s -w -X 'main.buildString=v2.0.0 (#05585b7 2021-09-29T08:59:00+0000)' -X 'main.versionString=v2.0.0'" cmd/*.go
cd frontend && /data/omnios-build/omniosorg/r151038/_extra/listmonk-2.0.0/listmonk-2.0.0/listmonk/_deps/node_modules/yarn/bin/yarn install
yarn install v1.22.11
[1/4] Resolving packages...
[2/4] Fetching packages...
/data/omnios-build/omniosorg/r151038/_extra/listmonk-2.0.0/listmonk-2.0.0/listmonk/_deps/bin/stuffbin -a stuff -in listmonk -out listmonk config.toml.sample schema.sql queries.sql static/public:/public …
> pack-bin is missing dependency on build-frontend

- static/public/static/style.css
Because it could be disturbing for people who are not confident with forms not being able to delete words before writing.
> Clear placeholder on focus

- frontend/src/App.vue
- frontend/src/components/Navigation.vue
I missed that the navbar logout button was moved back into App.vue in the previous commit.
> doLogout re-defined in App.vue

- static/email-templates/campaign-status.html
- static/email-templates/import-status.html
The alert emails (Campaign Status and Import Status) currently have broken links. This adds the `/admin` prefix to fix this,
> Fix alert email urls

- Makefile
- dev/README.md
- dev/app.Dockerfile
- dev/docker-compose.yml
Closes https://github.com/knadh/listmonk/issues/562
- Created a `dev/` folder with all the dev-docker specific files.
- The dev-docker setup is in such a way that the local app folder is mounted inside the container. This trick helps us to not do a `docker build` everytime there's a change in frontend/backend code.
- For frontend changes, since `vue` is automatically watching for changes, the live changes are seen in real time.
- For backend changes, since the `Go` app needs to be compiled, simply quit the current running setup and run `make dev-docker` again. That will run `make run` again, which would have new changes.
- There's a `make init-dev-docker` to run the DB Migrations for first time install.
These instructions are also inside `dev/README.md`.
P.S. I'd to create a new `make` …
> feat: Add dev docker setup

- install-prod.sh
Fixes https://github.com/knadh/listmonk/issues/624
Source https://unix.stackexchange.com/questions/230673/how-to-generate-a-random-string#comment393964_230684
> fix(install-prod.sh): Make `tr` work with macOS

- Dockerfile
- docker-compose.yml
Adds `tzdata` in the `Dockerfile` of the app so that
user can pass a `TZ` env variable to the container to configure
their timezone information.
Fixes https://github.com/knadh/listmonk/issues/637
> feat: Add timezone config in app container

- models/models.go
Having anchors created by the markdown parser allows to link directly to some part of the message.
This can be useful, for ex. if you want to create a table of contents within the message or when linking to the web version of the message.
(I didn’t sent a proposal before posting my PR since I read the contributing guidelines after coding and since it’s a really small PR, I hope you won’t mind)
> Add AutoHeadingID option to Markdown parser

- cmd/utils.go
Fixes #652 
**Changes**:
* Rename `tagRegexpSpaces` to `regexpSpaces`
* Replace whitespace with dash in names of uploaded files
> Fix #652: Replace whitespace with dash in names of uploaded files

- Makefile
- dev/.gitignore
- dev/README.md
- dev/config.toml
This PR suggests a few minor changes that should make the containerized dev stack a bit easier to start.
In it's current state the stack will error out on the `config.toml` file being absent, and that message easily gets buried under the rather verbose logs produced by the frontend stack. Likewise, initializing the database did not reliably work.
> Spiffy up containerized dev stack

- .gitattributes
Eslint complains on Windows about linebreaks not being LF, because they are the default CRLF on Windows. This change allows git to clone it with the expected EOL
> Added end of line config for git

- frontend/src/router/index.js
It showed "Logs" instead of "Maintenance" in the tab title
> Fix maintenance settings title

- static/public/templates/subscription-form.html
**What's the issue :**
Currently, there are no ids or aria-labels in the public subscription forms. These are helpful for accessibility.
[Link to issue](https://github.com/knadh/listmonk/issues/697)
**What's the solution:**
Add _for_ attribute to label tag and _id_ attribute to input tag. 
Label tag with _for_ attribute takes care of handling accessibility for input tag. Refer this document for more info [doc](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#accessibility_concerns)
**Screenshot of proof:**
> accessibility fix for subscription form

- internal/media/providers/s3/s3.go
> fix: check public URL before presigned URL generation

- frontend/src/api/index.js
- frontend/src/components/EmptyPlaceholder.vue
- frontend/src/components/LogView.vue
- frontend/src/components/Navigation.vue
- frontend/src/constants.js
- frontend/src/main.js
- frontend/src/views/404.vue
- frontend/src/views/CampaignAnalytics.vue
- frontend/src/views/Campaigns.vue
- frontend/src/views/Dashboard.vue
- frontend/src/views/Forms.vue
- frontend/src/views/Lists.vue
- frontend/src/views/Maintenance.vue
- frontend/src/views/SubscriberForm.vue
- frontend/src/views/settings/smtp.vue
This is more a "cosmetic" change but eslint worries about no-multiple-empty-lines rule
```
35:1  error  More than 1 blank line not allowed  no-multiple-empty-lines
```
So I had to options, ignore the rule or correct the sources…
Correcting the source seems to be the better option.
> correct eslint "no-multiple-empty-lines"

- frontend/package.json
- frontend/yarn.lock
Used `vue-cli` to upgrade all the dev deps from node v16 or lower (fixes #1245). Here are the steps followed
- `vue upgrade` to upgrade all deps to latest.
- remove `node_modules` directory and `yarn.lock` file.
- `yarn install` to install dependencies again.
> upgrade frontend dev deps to support node v17+

- .goreleaser.yml
Related to #544 
Updates `.goreleaser.yml` to compile binaries for aarch64, armhf and armv7. 
Tested on my fork of this repository.
> add support for arm binaries

- cmd/init.go
I wanted to add a copyright notification in the footer of my newsletters. I can use the `Date` function in the campaign body, but not in any of the `static/email-templates/*.html` files.
```diff
{{ define "footer" }}
</div>
<div class="footer">
<p>{{ L.T "public.poweredBy" }} <a href="https://listmonk.app" target="_blank">listmonk</a></p>
+        <small>&copy; {{ Date "2006" }}</small>
</div>
<div class="gutter">&nbsp;</div>
</body>
</html>
{{ end }}
```
Try to add the above modification, and:
```console
$ ./listmonk --static-dir=static
2023/03/25 15:30:13 main.go:99: v2.4.0 (c668523 2023-03-20T13:50:31Z)
2023/03/25 15:30:13 init.go:138: reading config: config.toml
2023/03/25 15:30:13 init.go:266: connecting to db: /var/run/postgresql/:5432/listmonk
2023/03/25 15:30:14 init.go:225: …
```
> Add more functions to notification template parsing

- .github/workflows/release.yml
- .goreleaser.yml
With the new recent changes in dockerhub[1], we should start pushing images to ghcr, and eventually phase out the existing dockerhub setup.
This PR adds a few configuration steps required to push images to ghcr alongside dockerhub.
[1]: https://blog.alexellis.io/docker-is-deleting-open-source-images/
> build: push docker image to ghcr.io

- .github/workflows/release.yml
- listmonk@.service
Proposed fix for #1310. 
Since v2.4.0, it looks like Listmonk is making system calls for changing resource limits, memory or scheduling parameters. This PR allows those system calls in the systemd service configuration. This allows Listmonk to run as a systemd service.
The downside of this change is that it weakens the sandbox around the Listmonk process when run as a systemd service. I don't fully understand how systemd works, but I don't expect any serious consequence.
> Enable extra system calls in systemd service

- .github/workflows/release.yml
- .goreleaser.yml
- Added docker build support for the following platforms:
- amd64 (default)
- arm64v8
- armv6
- armv7
- Added `GOOS` and `GOARCH` information to the `buildString`
- Added docker manifest details to store image architecture metadata
- Updated `docker/login-action` from `v1` to `v2`
- Updated `goreleaser/goreleaser-action` from `v2` to `v4`
Tested the images locally, built with `goreleaser` and seems to be working fine. Screenshots:
> feat: add multiarch docker build support

- docs/docs/content/apis/subscribers.md
The -u in curl is for user:password, not needed for this endpoint. Also the json payload was incorrect and the link to the section was also broken
> Fix docs for public subscription api

- docs/docs/content/configuration.md
Since `&& cd listmonk` was added to the installation, this path is changed.
> Update configuration.md - update path due to recent install path change

- docs/docs/content/apis/subscribers.md
The doc was missing the `Content-Type: application/json` header, making it unusable.
> 📝🐛 — Fix /api/subscribers/lists doc

- docker-compose.yml
listmonk is using alpine already, so why not use alpine for postgres too and save a few MB of network traffic and storage space.
> feat: docker compose with alpine for postgres

- cmd/campaigns.go
Create a copy of the campaign object before sending test message to each subscriber. This way the attachments are not shared between subscribers.
Fixes #1657
> Fix #1657 - Prevent adding attachments multiple times in campaign test messages

- listmonk-simple.service
https://github.com/knadh/listmonk/pull/1614#issuecomment-1868504363
> Update listmonk-simple.service - add optional log file

- docs/docs/content/installation.md
Integration with one-click deploy template for RepoCloud. This addition simplifies the process for users to quickly deploy and scale ListMonk using RepoCloud's efficient cloud hosting services.
> Added deploy template for RepoCloud.io

- README.md
- docs/docs/content/installation.md
- install-demo.sh
- install-prod.sh
Closes https://github.com/knadh/listmonk/issues/1740
Log on my macOS machine:
```
➜ ./install-prod.sh
>  checking for an existing docker db volume
>  fetching config.toml from listmonk repo
>  fetching docker-compose.yml from listmonk repo
>  generating a random password
>  modifying config.toml
>  modifying docker-compose.yml
>  running migrations
[+] Running 3/3
✔ Network test-listmonk_listmonk        Created                                                                                                                                      0.0s
✔ Volume "test-listmonk_listmonk-data"  Created                                                                                                                                      0.0s
✔ Container listmonk_db                 Started …
```
> fix: easy install docker script for macOS

- cmd/settings.go
- frontend/src/views/Settings.vue
Fixes https://github.com/knadh/listmonk/issues/1746 by adding backend and frontend sanitations for host inputs for SMTP and Bounce settings
> fix: trim config before use

- queries.sql
This PR fix a problem with the, where previously it couldn't handle alphanumeric strings effectively, for instance "Testing1234". 
The problem arises becuase of the limitations encountered with PostgreSQL's full-text search when dealing with alphanumeric strings. The core of the issue lies in the process of tokenization and indexing is optimized for natural language text and not for patterns that include numbers.
Full-text search breaks down text into tokens based on spaces and punctuation, then converts these tokens into lexemes. Alphanumeric strings might not be broken down or analyzed in a way that's useful for matching partial strings, especially when numbers are involved.
This can be easily demostrated with the following statements 
```sql
$ SELECT to_tsvector('Testing') @@ …
```
> fix: query campaign does not search numbers

- cmd/init.go
A very small addition to check http: Server closed error with proper errors.Is check, instead of strings.Contains
This is not a bugfix, or doesn't fix anything. Only makes the code a tiny bit more reliable and readable.
> fix: check errors.Is instead of strings.Contains for http: Server closed error

- docs/docs/content/templating.md
Pointing "Go template" hyperlink to actual Go template expression documentation.
> Update templating.md to include link to GO template expression documentation

- cmd/init.go
- internal/manager/manager.go
This is an attempt at implementing what is needed to make the RootURL variabe available in email templates.
addresses #1483
> make RootURL available in email templates

- internal/messenger/email/email.go
A trivial solution to implement exactly what is suggested on #1578, second option. In a lot of cases companies are required to keep a track record of all emails sent to clients. This is often achieved simply by bcc all emails to an archived mailbox. Of course, a perfect solution would be to implement archival at SMTP server side, but not all senders have this functionality. As an example discussed before in #1578, Amazon SES does not.
This feature addresses this. You can add a Bcc header at SMTP server configuration so that all emails sent by listmonk are copied.
> Implements feature #1578 - CC and BCC on custom headers

- docs/docs/content/bounces.md
Bounces seemingly aren't sent if this setting is only configured for the domain, needs to be configured for send-as email addresses also.
Per https://github.com/knadh/listmonk/issues/1807#issuecomment-2151855416
I made this change in my environment recently and will test it shortly.
> docs: add important step regarding ses in bounces.md

- Dockerfile
- Updated Dockerfile to use `--platform=$BUILDPLATFORM` for compatibility with multiple architectures
> fix(docker): support multi-platform builds

- docs/docs/content/configuration.md
I don't know if this is correct, but there's no info in the docs about these kinds of settings. All I could find was one comment here https://github.com/knadh/listmonk/issues/172 with some info.
I'm trying to figure out a solution to https://github.com/knadh/listmonk/issues/1717. I'm hoping that the larger the batch size, the longer the delay between retries will be, but I'm not sure if that's true.
I saw another "performance" section https://listmonk.app/docs/maintenance/performance/, but it's under "maintenance" so this seems more appropriate under "configuration".
> Update configuration.md +performance, batch size

- queries.sql
fixes: #1879
This issue occurred as the CTE query returned the id from campaign after inserting entry into campaign_lists table. But in this case, there is no insert happening and the result set returned was empty. Fixed the query to return id irrespective of insert happening in the campaign_lists table. 
Thanks,
Bowrna
> issue fix for clone campaign with empty list

- cmd/media.go
- cmd/utils.go
- docs/docs/content/apis/apis.md
- i18n/en.json
fixes: #1955 
This PR prevents uploading files with non-ascii characters. It returns an error message saying "Invalid filename 汉语.txt. Use only ASCII characters" with error code "422"
> add error message for filename with non-ascii chars

- docs/docs/content/apis/media.md
updating the api docs of media with missing API.
For media apis, retrieving a specific media using its id is missing. Updated that part in this PR.
> updating the api docs of media with missing api

- docs/docs/mkdocs.yml
with reference to this comment(https://github.com/knadh/listmonk/pull/1978#issuecomment-2274611875), missed to attach the newly created bounces docs under API in docs page. This PR fixes that part.
> attaching bounces api docs to the docs page

- docs/docs/content/querying-and-segmentation.md
I'm not sure if this is the correct place for this. Additionally, I wasn't sure if `campaign_views` should be added to the "Database fields" section at the top. 
Additionally, when I go to `/admin/subscribers` -> advanced search, and paste in `subscribers.email LIKE 'John%' AND status = 'blocklisted'`, I get an error notification: `Error fetching Subscribers: pq: column reference "status" is ambiguous`
Also, that error notification does not get logged, and disappears too fast. I think the time it stays visible should be increased, but I'm not sure how to do that.
I am trying to add these various commands to the docs: https://gist.github.com/MaximilianKohler/e5158fcfe6de80a9069926a67afcae11#postgresql
> Update querying-and-segmentation.md - Querying subscribers who viewed the campaign email

- internal/core/bounces.go
Issue - https://github.com/knadh/listmonk/issues/1979
Issue:
When making a GET request to the /api/bounces/{id} endpoint, the API was returning an error response:
`{"message":"Error fetching Bounce: pq: syntax error at or near "rder""}`
This error was caused by an incorrect placeholder replacement in the SQL query within the GetBounce function.
Fix:
- Updated the `GetBounce` function to use strings.ReplaceAll for replacing the `%order%` placeholder in the SQL query, similar to how it is done in the `QueryBounces` function.
- This ensures the placeholder is correctly substituted with the order clause "`id ASC`", resolving the syntax error.
Testing:
- Verified that the API now correctly fetches the bounce entry when making a GET request to `http://localhost:9000/api/bounces/{id}`, for tis …
> Fix #1979: syntax error in GetBounce method

- docker-compose.yml
The 'hostname' field in the docker-compose file is later used in Listmonk to generate the 'Message-Id' of each mail. The hostname is used as the id-right section of 'Message-Id'.
According to RFC 2822 3.6.4, id-right = dot-atom-text / no-fold-literal / obs-id-right
Also, Rspamd has a spam filtering field 'MID_RHS_NOT_FQDN' which defaults to a 1.0 score.
https://github.com/rspamd/rspamd/blob/8b8211ac701e76a1ad474da5c6976769ba310f6c/rules/mid.lua#L29
This commit suggests an FQDN in the docker-compose file, which is guaranteed to meet the requirement.
> docs: suggest an FQDN in docker compose file

- docs/docs/content/apis/lists.md
The docs say that `tags` is a query param, but it's actually `tag`, as seen here:
https://github.com/knadh/listmonk/blob/51e3f1789bade0c416e8bea8b3b1eccef39399b7/cmd/lists.go#L19
> Fix tag query param in lists.md

- README.md
'software', when used as a noun, is not a 'countable' type, and it does not get an article like 'a'.  It's like 'traffic'.
> nit:  English

- cmd/subscribers.go
- frontend/src/views/Subscribers.vue
- internal/core/subscribers.go
- internal/core/subscriptions.go
- models/queries.go
- queries.sql
fixes: #1841
related_to: #1985
This issue existed as the subscription_status filter was not passed to the backend. Added a fix by including a new param to send the status, and altered the numbering in parameterized query.
The query affected is a base query template. So all the queries using this base query were in turn affected.
> passed the subscription_status param

- docker-compose.yml
- install-prod.sh
fixing troubles I had while getting started
> Slightly improve docker-compose feedback

- frontend/src/components/HTMLEditor.vue
This PR adds word wrap functionality to the HTML editor, addressing issue #1806. 
It improves the user experience by eliminating the need for horizontal scrolling 
for long lines of HTML.
- Updated the CodeFlask initialization to include `lineWrapping: true`
This change doesn't affect the underlying HTML content, only its display in the editor.
> misc:add word wrap to HTML editor

- docs/swagger/collections.yaml
- frontend/src/views/Import.vue
- i18n/en.json
related: #2057 
closes: #2057
I added a fix that sets the overwrite switch as off by default and shows a warning message when trying to import after switch on the overwrite option. I have added the i18n string in en.json file and when testing locally, I could see the i18n key alone. I am not sure if it involves any additional steps to get the translation working. If anyone could guide me on that part, it would be useful.
> import warning and setting overwrite default off

- frontend/package.json
- frontend/src/assets/style.scss
- frontend/src/components/Editor.vue
- frontend/src/components/MarkdownEditor.vue
related: #2058 
Added fix to support markdown syntax highlighter. As code-flask doesn't support markdown by default, I had to import prism-markdown. Added styles in shadow DOM as style from prismjs doesn't percolate/get injected into shadow DOM.
Let me know if anything has to be modified/ fixed in this PR.
> markdown syntax highlighter

- frontend/src/views/Settings.vue
Dummy detection for OIDC client secret does not work because wrong symbol is referenced. This causes that the OIDC client secret is overridden by a dummy secret when user saves application settings. This change fixes this issue.
> fix dummy detection for OIDC client secret

- docs/site/layouts/partials/header.html
- static/public/templates/index.html
- Removed `rel="shortcut"` [because](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel#icon)
> The `shortcut` link type is often seen before `icon`, but this link type is non-conforming, ignored and **web authors must not use it anymore**.
- Corrected media type for PNG favicons.
For a custom favicon we currently always set `type="image/x-icon"` which is a media type [for ICO files](https://en.wikipedia.org/wiki/ICO_%28file_format%29#MIME_type). 
Instead, I'd like to change the template to infer the media type from the actually provided file's extension, but I think this is impossible with only the [functions built into the html/template package](https://coveooss.github.io/gotemplate/docs/functions_reference/base-go-template-functions/) and we'd have to first define …
> fix: favicon markup

- Dockerfile
Removed `--platform=$BUILDPLATFORM` from the `Dockerfile` this was overriding the buildx configuration set by goreleaser.yaml .
Assuming that a new release was created, and published to DockerHub and the following commands are run on a Arm64 machine:
```shell
$ docker run -ti --rm --entrypoint /bin/sh knadh/listmonk:latest
```
```shell
$ apk add file
```
```shell
$ file /bin/busybox
/bin/busybox: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-aarch64.so.1, BuildID[sha1]=0473dd0398a4d4c4f29ebed5a94f63d78096563e, stripped
```
The output of the `file /bin/busybox` should include `ARM aarch64` meaning that the base image is Arm64.
> #2114 - Fix issue of wrong platform used during docker build

- docs/docs/content/apis/lists.md
- docs/swagger/collections.yaml
In order to create a correct client library this is needed in `collection.yaml`.
> adds property `description` to `List` and `NewList`, updates docs

- frontend/src/views/Campaign.vue
Starting with v4.0, it was impossible to select any messenger besides email for a campaign due to an issue loading the messenger list from the API on line 629 of Campaign.vue.
The change was making m.name be just m since the messengers are listed as an array of strings on /api/config
> Corrected loading of messengers from serverConfig on line 629

- .devcontainer/devcontainer.json
- dev/app.Dockerfile
- dev/config.toml
- dev/docker-compose.yml
- docs/docs/content/developer-setup.md
**Changes**:
- Upgrade golang to 1.20
- Modify dev's config (conform to prod's, and fix dev db credential)
- Add support for devcontainers
- Update docs for dev environment setup
Fix #2199
> Fix outdated docker local dev suite

- cmd/events.go
- cmd/utils.go
- internal/captcha/captcha.go
- internal/manager/manager.go
- internal/messenger/email/email.go
- internal/subimporter/importer.go
1.Updated Usage of strings.Title:
Replaced the deprecated strings.Title function with golang.org/x/text/cases for handling Unicode punctuation properly.
2.Resolved Syntax Issue in email.go:
Fixed syntax in internal/messenger/email/email.go at line 33
3.Resolved Syntax Issue in captcha.go:
Addressed a syntax issue in internal/captcha/captcha.go at line 67.
> Refactor backend

- docs/docs/content/apis/sdks.md
This PR adds the [Listmonk Laravel Package](https://packagist.org/packages/theafolayan/listmonk-laravel) to the List of available SDKs.
> Docs: Add Laravel SDK to Supported Libraries Lists

- cmd/bounce.go
- frontend/package.json
- frontend/yarn.lock
- internal/bounce/webhooks/forwardemail.go
Fixes the forwardemail bounce processing and adds some checks (encoding / payload types) to signature validation. Relates to: https://github.com/knadh/listmonk/discussions/2246
Also fixes frontend build issues around yarn caching blocking developer setup / install (make dist) described here: https://github.com/storybookjs/storybook/issues/22431#issuecomment-1630086092
Happy to move that 2nd item that changes frontend (yarn.lock / package.json) to another PR if needed. It looks like build is blocked though without it.
> fix: forwardemail bounce processing invalid signature issue

- frontend/src/App.vue
I was setting up Listmonk and noticed there was a typo in the callout.
<details><summary>Screenshot</summary>
<p>
</p>
</details> 
---
Thanks for listmonk, Kailash! 💖
> fix: typo in callout under the settings page

- frontend/src/assets/style.scss
- frontend/src/components/LogView.vue
This PR enhances the log parsing functionality by updating the regex to support milliseconds ([#30be235](https://github.com/knadh/listmonk/commit/30be235e2ab87697d563f0adc8fef8d72a8f3ce6)) in LogView.vue. Additionally, the .file class was merged with .timestamp in styles.scss, ensuring consistent styling and allowing users to select both elements together with proper spacing.
> Fix: LogView regex for milliseconds & add span file support

- i18n/cs-cz.json
This PR fixes unclear wording, where it might seem like user has unsubscribed when they confirmed the subscription.
> Fix ambiguity in cs-cz translation

- docs/docs/content/bounces.md
The AWS Console now has "Identities" instead of "Verified Identities" in the left sidebar. This PR just updates the docs to match.
> Updating documentation to reflect AWS Console changes

- models/models.go
Hi there!
First, thank you for developing and maintaining listmonk - it's an awesome tool and very easy to use!
I implemented listmonk at my company a few weeks ago, and one recurring issue reported by the marketing team is that they sometimes cannot save tracked links.
After investigating, I found that the issue stems from the TrackLink regex replacement, which incorrectly matches more characters than intended. This results in template compilation errors like:
```
{"message":"Error compiling template: error compiling message: template: content:1: unexpected \"\u003e\" in operand"}
```
A minimal reproducible example is inserting two links in the same line:
```html
<a href="https://google.de">Untracked Link</a><a href="https://google.de@TrackLink">Tracked Link</a>
```
This causes the …
> Fix too greedy TrackLink regex replacement.

- frontend/src/views/Import.vue
The example raw CSV given did not work as an import, and according to the [documentation of the function that raised the error](https://pkg.go.dev/net/mail#ParseAddress), `ParseAdress`, the verification of the validity of mails is done according to [RFC 5322](https://www.rfc-editor.org/rfc/rfc5322.html), which specifies that the local part  of the mail (before the `@`) cannot contain spaces if it is not quoted
In [section 3.4.1](https://www.rfc-editor.org/rfc/rfc5322.html#section-3.4.1):
> The locally
interpreted string is either a quoted-string or a dot-atom.  If the
string can be represented as a dot-atom (that is, it contains no
characters other than atext characters or "." surrounded by atext
characters), then the dot-atom form SHOULD be used and the quoted-
string form SHOULD NOT be …
> Changed Raw CSV example in the import page to comply with RFC 5322

- models/models.go
Hi @knadh,
I noticed an additional oversight in my last MR #2355. 
`\p{L}` does not include numbers... :man_facepalming: 
Here's the fix, adding `\p{N}`. Sorry bout that!
> TrackLink regex: Add missing charset for numbers.

- docs/site/layouts/index.html
Add Kloudbean URL for Hosting in `docs/site/layouts/index.html`.
> Add Kloudbean Hosting Link

- docs/docs/content/templating.md
Issue mentioned in #2526 
This pull request adds a new section to the templating documentation to support campaigns. The most important change introduces template expressions for accessing campaign-related data.
Documentation updates:
* [`docs/docs/content/templating.md`](diffhunk://#diff-343d376cb084447fe4c20472fedaf29731f454aeb1bafa808cbd56408fb474ebR34-R35): Added a new "Campaigns" section with template expressions, including `{{ .Campaign.UUID }}` to retrieve the unique ID of a campaign.
> Add missing header for campaigns in template

- internal/subimporter/importer.go
Closes issue #2541 
Just a small change to the `countLines` function which just checks if the last byte is a line break (`\n`) and adds one to the total count if it's not. This means that the row count remains more accurate if there is no trailing line break.
This does not introduce any logic to distinguish between "blank" and non "blank" lines and therefore still does not guarantee an accurate row count (even just in the case of multiple trailing line breaks), but does approach a _more_ accurate row count.
> Update countLines for improved accuracy

- docs/docs/content/apis/sdks.md
- Add listmonk-mcp to the community SDKs documentation page
- MCP (Model Context Protocol) server provides Claude integration for listmonk
> Add listmonk-mcp to SDKs documentation

- internal/bounce/webhooks/postmark.go
The code attempts to do this by handling the `SpamComplaint` `Type` however this is sent with a `RecordType` of `SpamComplaint` rather than `Bounce` so is ignored. Accepting this additional `RecordType` solves the issue.
This behaviour is described in Postmark's documentation.
> Note that that spam complaints, unsubscribes/subscribes, or manual deactivations have their own webhooks and are not trigged via the Bounce webhook.
>
> https://postmarkapp.com/developer/webhooks/bounce-webhook
https://postmarkapp.com/developer/webhooks/spam-complaint-webhook#spam-complaint-webhook-data
> Handle Postmark spam complaints.
